### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by tawheeler** [shashi/Reel.jl#12]
@shashi - I'd like to set up Travis similar to [this](https://travis-ci.org/sisl/BayesNets.jl). The problem is that the package is under shashi/Reel, so I cannot enable testing for it on Travis. I believe it is free. Any chance you could set that up?

You need to:
- create an account on Travis
- sync it with your Github repos
- enable Travis for Reel.jl

Anyone pushing to Reel.jl that should automatically trigger a new Travis build.

![image](https://cloud.githubusercontent.com/assets/3334079/19637449/77d36ada-99cf-11e6-8e9e-13c0c9f89a68.png)

**Comment by shashi** [comment]
I've enabled Travis. Thanks for doing this!

**Comment by tawheeler** [comment]
Thanks!
