### ISSUE TITLE
Using which on Windows

### ISSUE THREAD

**Issue by mykelk** [shashi/Reel.jl#14]
This doesn't seem to work on Windows (currently starting at line 71 of src/Reel.jl):
```julia
        cmd = try readstring(`which convert`)
        catch e1
            try readstring(`which magick`)
            catch e2
                error("Could not find imagemagick binary. Is it installed?")
            end
        end |> strip
```
The command `which` is not supported. We end up getting this error:
```
Could not find imagemagick binary. Is it installed?
```
when it is actually installed.

**Comment by tawheeler** [comment]
I tried using the `where` command on windows instead. Unfortunately travis does not support testing on windows, so I'm not sure I can check whether it worked.

**Comment by mykelk** [comment]
Yep, `where` works perfectly. One needs to be careful about `convert` since that is a command on Windows that converts a FAT volume to NTFS. Does it make sense to use https://github.com/JuliaIO/ImageMagick.jl?

**Comment by tawheeler** [comment]
Okay, created a new tag.
Switching to ImageMagick would be a good idea. Will add a new issue for that.
