### ISSUE TITLE
Could not find imagemagick binary. Is it installed?

### ISSUE THREAD

**Issue by Shushman** [shashi/Reel.jl#26]
I get the above message while testing `Reel` as per this commit - https://github.com/Shushman/Reel.jl/tree/dd46ffc03a88531c8c511a817a6cb441b443d178

Does `Reel` need `ImageMagick`? I see #15 has something to say about that - is it related?

**Comment by tawheeler** [comment]
I think ImageMagick was required to ensure that some of the image manipulation utilities (pdf2svg maybe? I forget.) are installed on the local system. It may not longer be necessary.

**Comment by Shushman** [comment]
Ah, just had to do with `readstring -> read`
