### ISSUE TITLE
Imagemagick convert command replaced

### ISSUE THREAD

**Issue by MaximeBouton** [shashi/Reel.jl#9]
The 'convert' command of imagemagick has been replaced by `magick` in the latest version. It needs to be replaced if you want to export in gif.

**Comment by shashi** [comment]
Hmm, would it make sense to first check to see if `convert` exists and call `magick` if it doesn't

**Comment by MaximeBouton** [comment]
It would make sense, though on windows system there is an existing `convert` command that does something else, I can check if there is a conflict.
